# https://taskfile.dev

version: '3'
includes:
    cenv: deps.setup.conda-env.exe.yml
vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task -l
    silent: true
